// LendCity configuration — update these values as needed
export const LENDCITY = {
  name: 'LendCity',
  website: 'https://lendcity.ca',
  title: 'LendCity Mortgages – Licensed Mortgage Professionals in Canada',
  brokerage: 'Mortgage Architects',
  license: 'FSRA Brokerage Licence #12728',
  bookingUrl: '/book-a-call',
  phone: '1-519-960-0370',
  streetAddress: '4769 Wyandotte St E',
  city: 'Windsor',
  province: 'Ontario',
  provinceCode: 'ON',
  postalCode: 'N8Y 1H8',
  country: 'Canada',
  countryCode: 'CA',
  addressFormatted: '4769 Wyandotte St E, Windsor, Ontario, N8Y 1H8',
  logo: '/images/lendcity-logo.webp',
  tagline: 'From First Lesson to First Home',
} as const;
